// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sugira.Data;

#nullable disable

namespace Sugira.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sugira.Models.CategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MenuId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Sugira.Models.CharacteristicOptionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacteristicTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CharacteristicTypeId");

                    b.ToTable("CharacteristicOption");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CharacteristicTypeId = 1,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(4553),
                            IsActive = true,
                            Value = "Leve"
                        },
                        new
                        {
                            Id = 2,
                            CharacteristicTypeId = 1,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5276),
                            IsActive = true,
                            Value = "Moderado"
                        },
                        new
                        {
                            Id = 3,
                            CharacteristicTypeId = 1,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5278),
                            IsActive = true,
                            Value = "Amargo"
                        },
                        new
                        {
                            Id = 4,
                            CharacteristicTypeId = 1,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5279),
                            IsActive = true,
                            Value = "Intenso"
                        },
                        new
                        {
                            Id = 5,
                            CharacteristicTypeId = 2,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5280),
                            IsActive = true,
                            Value = "Baixo"
                        },
                        new
                        {
                            Id = 6,
                            CharacteristicTypeId = 2,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5281),
                            IsActive = true,
                            Value = "Equilibrado"
                        },
                        new
                        {
                            Id = 7,
                            CharacteristicTypeId = 2,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5282),
                            IsActive = true,
                            Value = "Alto"
                        },
                        new
                        {
                            Id = 8,
                            CharacteristicTypeId = 3,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5283),
                            IsActive = true,
                            Value = "Baixo"
                        },
                        new
                        {
                            Id = 9,
                            CharacteristicTypeId = 3,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5284),
                            IsActive = true,
                            Value = "Moderado"
                        },
                        new
                        {
                            Id = 10,
                            CharacteristicTypeId = 3,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5286),
                            IsActive = true,
                            Value = "Alto"
                        },
                        new
                        {
                            Id = 11,
                            CharacteristicTypeId = 3,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5287),
                            IsActive = true,
                            Value = "Muito alto"
                        },
                        new
                        {
                            Id = 12,
                            CharacteristicTypeId = 4,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5287),
                            IsActive = true,
                            Value = "Adocicado"
                        },
                        new
                        {
                            Id = 13,
                            CharacteristicTypeId = 4,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5288),
                            IsActive = true,
                            Value = "Cítrico"
                        },
                        new
                        {
                            Id = 14,
                            CharacteristicTypeId = 4,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5289),
                            IsActive = true,
                            Value = "Torrado"
                        },
                        new
                        {
                            Id = 15,
                            CharacteristicTypeId = 4,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5290),
                            IsActive = true,
                            Value = "Grãos"
                        },
                        new
                        {
                            Id = 16,
                            CharacteristicTypeId = 4,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5291),
                            IsActive = true,
                            Value = "Salgado"
                        },
                        new
                        {
                            Id = 17,
                            CharacteristicTypeId = 4,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5292),
                            IsActive = true,
                            Value = "Herbal"
                        },
                        new
                        {
                            Id = 18,
                            CharacteristicTypeId = 4,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5293),
                            IsActive = true,
                            Value = "Defumado"
                        },
                        new
                        {
                            Id = 19,
                            CharacteristicTypeId = 4,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5294),
                            IsActive = true,
                            Value = "Frutado"
                        },
                        new
                        {
                            Id = 20,
                            CharacteristicTypeId = 4,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5294),
                            IsActive = true,
                            Value = "Maltado"
                        },
                        new
                        {
                            Id = 21,
                            CharacteristicTypeId = 5,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5295),
                            IsActive = true,
                            Value = "Leve"
                        },
                        new
                        {
                            Id = 22,
                            CharacteristicTypeId = 5,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5296),
                            IsActive = true,
                            Value = "Cremoso"
                        },
                        new
                        {
                            Id = 23,
                            CharacteristicTypeId = 5,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5297),
                            IsActive = true,
                            Value = "Seco"
                        },
                        new
                        {
                            Id = 24,
                            CharacteristicTypeId = 5,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5298),
                            IsActive = true,
                            Value = "Encorpado"
                        },
                        new
                        {
                            Id = 25,
                            CharacteristicTypeId = 5,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5313),
                            IsActive = true,
                            Value = "Aveludado"
                        },
                        new
                        {
                            Id = 26,
                            CharacteristicTypeId = 6,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5313),
                            IsActive = true,
                            Value = "Clara"
                        },
                        new
                        {
                            Id = 27,
                            CharacteristicTypeId = 6,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5314),
                            IsActive = true,
                            Value = "Dourada"
                        },
                        new
                        {
                            Id = 28,
                            CharacteristicTypeId = 6,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5315),
                            IsActive = true,
                            Value = "Âmbar"
                        },
                        new
                        {
                            Id = 29,
                            CharacteristicTypeId = 6,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5316),
                            IsActive = true,
                            Value = "Cobre"
                        },
                        new
                        {
                            Id = 30,
                            CharacteristicTypeId = 6,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5317),
                            IsActive = true,
                            Value = "Marrom"
                        },
                        new
                        {
                            Id = 31,
                            CharacteristicTypeId = 6,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5318),
                            IsActive = true,
                            Value = "Preta"
                        },
                        new
                        {
                            Id = 32,
                            CharacteristicTypeId = 7,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5319),
                            IsActive = true,
                            Value = "Baixa"
                        },
                        new
                        {
                            Id = 33,
                            CharacteristicTypeId = 7,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5363),
                            IsActive = true,
                            Value = "Média"
                        },
                        new
                        {
                            Id = 34,
                            CharacteristicTypeId = 7,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5364),
                            IsActive = true,
                            Value = "Alta"
                        },
                        new
                        {
                            Id = 35,
                            CharacteristicTypeId = 8,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5365),
                            IsActive = true,
                            Value = "Mal passado"
                        },
                        new
                        {
                            Id = 36,
                            CharacteristicTypeId = 8,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5366),
                            IsActive = true,
                            Value = "Ao ponto"
                        },
                        new
                        {
                            Id = 37,
                            CharacteristicTypeId = 8,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5367),
                            IsActive = true,
                            Value = "Bem passado"
                        },
                        new
                        {
                            Id = 38,
                            CharacteristicTypeId = 9,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5367),
                            IsActive = true,
                            Value = "Frio"
                        },
                        new
                        {
                            Id = 39,
                            CharacteristicTypeId = 9,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5368),
                            IsActive = true,
                            Value = "Morno"
                        },
                        new
                        {
                            Id = 40,
                            CharacteristicTypeId = 9,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5369),
                            IsActive = true,
                            Value = "Quente"
                        },
                        new
                        {
                            Id = 41,
                            CharacteristicTypeId = 10,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5370),
                            IsActive = true,
                            Value = "Sem tempero"
                        },
                        new
                        {
                            Id = 42,
                            CharacteristicTypeId = 10,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5371),
                            IsActive = true,
                            Value = "Leve"
                        },
                        new
                        {
                            Id = 43,
                            CharacteristicTypeId = 10,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5372),
                            IsActive = true,
                            Value = "Moderado"
                        },
                        new
                        {
                            Id = 44,
                            CharacteristicTypeId = 10,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5373),
                            IsActive = true,
                            Value = "Intenso"
                        },
                        new
                        {
                            Id = 45,
                            CharacteristicTypeId = 11,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5374),
                            IsActive = true,
                            Value = "Baixa"
                        },
                        new
                        {
                            Id = 46,
                            CharacteristicTypeId = 11,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5374),
                            IsActive = true,
                            Value = "Moderada"
                        },
                        new
                        {
                            Id = 47,
                            CharacteristicTypeId = 11,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5375),
                            IsActive = true,
                            Value = "Alta"
                        },
                        new
                        {
                            Id = 48,
                            CharacteristicTypeId = 12,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5376),
                            IsActive = true,
                            Value = "Sem ardência"
                        },
                        new
                        {
                            Id = 49,
                            CharacteristicTypeId = 12,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5377),
                            IsActive = true,
                            Value = "Leve"
                        },
                        new
                        {
                            Id = 50,
                            CharacteristicTypeId = 12,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5378),
                            IsActive = true,
                            Value = "Moderada"
                        },
                        new
                        {
                            Id = 51,
                            CharacteristicTypeId = 12,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5379),
                            IsActive = true,
                            Value = "Alta"
                        },
                        new
                        {
                            Id = 52,
                            CharacteristicTypeId = 13,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5379),
                            IsActive = true,
                            Value = "269ml"
                        },
                        new
                        {
                            Id = 53,
                            CharacteristicTypeId = 13,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5380),
                            IsActive = true,
                            Value = "350ml"
                        },
                        new
                        {
                            Id = 54,
                            CharacteristicTypeId = 13,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5381),
                            IsActive = true,
                            Value = "355ml"
                        },
                        new
                        {
                            Id = 55,
                            CharacteristicTypeId = 13,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5382),
                            IsActive = true,
                            Value = "473ml"
                        },
                        new
                        {
                            Id = 56,
                            CharacteristicTypeId = 13,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5383),
                            IsActive = true,
                            Value = "600ml"
                        },
                        new
                        {
                            Id = 57,
                            CharacteristicTypeId = 13,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5384),
                            IsActive = true,
                            Value = "1L"
                        },
                        new
                        {
                            Id = 58,
                            CharacteristicTypeId = 14,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5384),
                            IsActive = true,
                            Value = "Pequeno"
                        },
                        new
                        {
                            Id = 59,
                            CharacteristicTypeId = 14,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5385),
                            IsActive = true,
                            Value = "Médio"
                        },
                        new
                        {
                            Id = 60,
                            CharacteristicTypeId = 14,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5386),
                            IsActive = true,
                            Value = "Grande"
                        },
                        new
                        {
                            Id = 61,
                            CharacteristicTypeId = 15,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5387),
                            IsActive = true,
                            Value = "Com molho"
                        },
                        new
                        {
                            Id = 62,
                            CharacteristicTypeId = 15,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 862, DateTimeKind.Utc).AddTicks(5388),
                            IsActive = true,
                            Value = "Sem molho"
                        });
                });

            modelBuilder.Entity("Sugira.Models.CharacteristicTypeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("CharacteristicType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 860, DateTimeKind.Utc).AddTicks(7162),
                            IsActive = true,
                            Name = "Amargura"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 860, DateTimeKind.Utc).AddTicks(7805),
                            IsActive = true,
                            Name = "Doçura"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 860, DateTimeKind.Utc).AddTicks(7808),
                            IsActive = true,
                            Name = "Teor Alcoólico"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 860, DateTimeKind.Utc).AddTicks(7809),
                            IsActive = true,
                            Name = "Sabor"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 860, DateTimeKind.Utc).AddTicks(7809),
                            IsActive = true,
                            Name = "Textura"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 860, DateTimeKind.Utc).AddTicks(7810),
                            IsActive = true,
                            Name = "Cor"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 860, DateTimeKind.Utc).AddTicks(7811),
                            IsActive = true,
                            Name = "Carbonatação"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 860, DateTimeKind.Utc).AddTicks(7812),
                            IsActive = true,
                            Name = "Ponto"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 860, DateTimeKind.Utc).AddTicks(7813),
                            IsActive = true,
                            Name = "Temperatura"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 860, DateTimeKind.Utc).AddTicks(7814),
                            IsActive = true,
                            Name = "Tempero"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 860, DateTimeKind.Utc).AddTicks(7814),
                            IsActive = true,
                            Name = "Acidez"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 860, DateTimeKind.Utc).AddTicks(7815),
                            IsActive = true,
                            Name = "Ardência"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 860, DateTimeKind.Utc).AddTicks(7816),
                            IsActive = true,
                            Name = "Volume"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 860, DateTimeKind.Utc).AddTicks(7817),
                            IsActive = true,
                            Name = "Tamanho"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 8, 29, 16, 4, 53, 860, DateTimeKind.Utc).AddTicks(7818),
                            IsActive = true,
                            Name = "Molho"
                        });
                });

            modelBuilder.Entity("Sugira.Models.ItemCharacteristicModel", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("CharacteristicTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("CharacteristicOptionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("ItemId", "CharacteristicTypeId", "CharacteristicOptionId");

                    b.HasIndex("CharacteristicOptionId");

                    b.HasIndex("CharacteristicTypeId");

                    b.ToTable("ItemCharacteristic");
                });

            modelBuilder.Entity("Sugira.Models.ItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("Sugira.Models.ItemPhotoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemPhoto");
                });

            modelBuilder.Entity("Sugira.Models.MenuModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("Sugira.Models.CategoryModel", b =>
                {
                    b.HasOne("Sugira.Models.MenuModel", "Menu")
                        .WithMany("Categories")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Sugira.Models.CharacteristicOptionModel", b =>
                {
                    b.HasOne("Sugira.Models.CharacteristicTypeModel", "CharacteristicType")
                        .WithMany("Options")
                        .HasForeignKey("CharacteristicTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacteristicType");
                });

            modelBuilder.Entity("Sugira.Models.ItemCharacteristicModel", b =>
                {
                    b.HasOne("Sugira.Models.CharacteristicOptionModel", "CharacteristicOption")
                        .WithMany()
                        .HasForeignKey("CharacteristicOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sugira.Models.CharacteristicTypeModel", "CharacteristicType")
                        .WithMany()
                        .HasForeignKey("CharacteristicTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sugira.Models.ItemModel", "Item")
                        .WithMany("Characteristics")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacteristicOption");

                    b.Navigation("CharacteristicType");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Sugira.Models.ItemModel", b =>
                {
                    b.HasOne("Sugira.Models.CategoryModel", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Sugira.Models.ItemPhotoModel", b =>
                {
                    b.HasOne("Sugira.Models.ItemModel", "Item")
                        .WithMany("Photos")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Sugira.Models.CategoryModel", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Sugira.Models.CharacteristicTypeModel", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("Sugira.Models.ItemModel", b =>
                {
                    b.Navigation("Characteristics");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Sugira.Models.MenuModel", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
